title: "阿男的小窝"
author: "阿男"
email: l.weinan@gmail.com
#google_analytics: UA-98502720-1
disqus:
   shortname: weinan-io
#theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 50
webmaster_verifications:
  baidu: H3WlhxyTrS
